--CARGA DE IMAGENES UTILIZANDO VARIABLES DE TIPO BLOB
CREATE OR REPLACE DIRECTORY IMAGENES_CARA AS 'C:\imagenes_Proyecto_Bases_2\Caras\';

--CONECTARNOS CON EL USUARIO SYSTEM (TODO DESDE OTRO USUARIO SYSTEM OJO)------(OTORGAR PERMISOS AL USUARIO)
GRANT READ,WRITE ON DIRECTORY IMAGENES_CARA TO USER_PROYECTO;

--CREAMOS LA TABLA DONDE TENDREMOS LA IMAGEN
CREATE TABLE FACE(
    id NUMBER PRIMARY KEY,
    face_img BLOB DEFAULT EMPTY_BLOB()
);

--CREAMOS EL PROCESO PARA LA CARGA DE IMAGEN
DECLARE
    V_TEMP BLOB;    -- GUARDA TEMPORALMENTE LA VARIABLE QUE ESTA EN LA RUTA
    V_BFILE BFILE;  -- BUSCA EL ARCHIVO PARA SABER SI EXISTE
    V_NAME_IMAGE VARCHAR(20);   -- GUARDA EL NOMBRE DE LA IMAGEN

BEGIN
    --INSERT
            -- INSERT INTO CAR VALUES(100,'111','222',EMPTY_BLOB());  CON ESTA SENTENCIA PODEMOS COMPROBAR QUE SI SE INSERTA EN LA TABLA PERO VACIO EL ESPACIO DE LA IMAGEN

    INSERT INTO FACE VALUES(4,EMPTY_BLOB()) Returning face_img INTO V_TEMP;

    V_NAME_IMAGE := '4.jpg';

    V_BFILE := BFILENAME('IMAGENES_CARA',V_NAME_IMAGE);   --SI LA IMAGEN (V_NAME_IMAGE) EXISTE EN EL DIRECTORIO (OBJETOS_LOB) SE GUARDA EN V_BFILE

    DBMS_LOB.OPEN(V_BFILE,DBMS_LOB.LOB_READONLY);       --LUEGO SE ABRE LA IMAGEN (V_BFILE) COMO LECTURA

    DBMS_LOB.LOADFROMFILE(V_TEMP,V_BFILE,DBMS_LOB.GETLENGTH(V_BFILE));      --GUARDAMOS SOBRE (V_TEMP) LA IMAGEN ENCONTRADA (V_BFILE) Y EL TAMANO EN MB O KB

    DBMS_LOB.CLOSE(V_BFILE);        --CERRAMOS LA VARIABLE V_BFILE

    COMMIT;

END;

select * from face;