create or replace NONEDITIONABLE PROCEDURE INSERTAR_SUCURSALES(direccion_sucursal varchar, descripcion_sucursal varchar, horario_sucursal varchar)
IS
    --CREATE OR REPLACE DIRECTORY IMAGENES_SUCURSAL AS 'C:\imagenes_Proyecto_Bases_2\Sucursal\';
    --GRANT READ,WRITE ON DIRECTORY IMAGENES_SUCURSAL TO USER_PROYECTO;
BEGIN
    DECLARE
        V_TEMP BLOB;    -- GUARDA TEMPORALMENTE LA VARIABLE QUE ESTA EN LA RUTA
        V_BFILE BFILE;  -- BUSCA EL ARCHIVO PARA SABER SI EXISTE
        V_NAME_IMAGE VARCHAR(50);   -- GUARDA EL NOMBRE DE LA IMAGEN
        descripcion varchar(50);

    BEGIN
    
        --INSERT
        
        descripcion:='La ' || descripcion_sucursal || ' comida';
      
        INSERT INTO SUCURSAL VALUES(SEQ_SUCURSAL.NEXTVAL,direccion_sucursal,descripcion,EMPTY_BLOB(), horario_sucursal,1) Returning MAPA INTO V_TEMP;
        
        V_NAME_IMAGE := direccion_sucursal||'.jpg';

        V_BFILE := BFILENAME('IMAGENES_SUCURSAL',V_NAME_IMAGE);   --SI LA IMAGEN (V_NAME_IMAGE) EXISTE EN EL DIRECTORIO (OBJETOS_LOB) SE GUARDA EN V_BFILE

        DBMS_LOB.OPEN(V_BFILE,DBMS_LOB.LOB_READONLY);       --LUEGO SE ABRE LA IMAGEN (V_BFILE) COMO LECTURA

        DBMS_LOB.LOADFROMFILE(V_TEMP,V_BFILE,DBMS_LOB.GETLENGTH(V_BFILE));      --GUARDAMOS SOBRE (V_TEMP) LA IMAGEN ENCONTRADA (V_BFILE) Y EL TAMANO EN MB O KB

        DBMS_LOB.CLOSE(V_BFILE);        --CERRAMOS LA VARIABLE V_BFILE

        COMMIT;

    END;
END;