create or replace procedure INSERTAR_PRODUCTO(NOMBRE VARCHAR, PRECIO NUMBER,UNIDAD VARCHAR, CANT_MINIMA VARCHAR)
is 
Begin
    DECLARE
        V_TEMP BLOB;    -- GUARDA TEMPORALMENTE LA VARIABLE QUE ESTA EN LA RUTA
        V_BFILE BFILE;  -- BUSCA EL ARCHIVO PARA SABER SI EXISTE
        V_NAME_IMAGE VARCHAR(50);   -- GUARDA EL NOMBRE DE LA IMAGEN

    --CREATE OR REPLACE DIRECTORY IMAGENES_PRODUCTO AS 'C:\imagenes_Proyecto_Bases_2\Producto\';
    --GRANT READ,WRITE ON DIRECTORY IMAGENES_PRODUCTO TO USER_PROYECTO;

    BEGIN
        --INSERT

        INSERT INTO PRODUCTO VALUES(NOMBRE,SEQ_PRODUCTO.NEXTVAL,EMPTY_BLOB(),MONTO(MONTO.VALIDATE_MONTO(PRECIO),'$'),UNIDAD, CANT_MINIMA) Returning FOTO INTO V_TEMP;

        V_NAME_IMAGE := NOMBRE ||'.jpg';

        V_BFILE := BFILENAME('IMAGENES_PRODUCTO',V_NAME_IMAGE);   --SI LA IMAGEN (V_NAME_IMAGE) EXISTE EN EL DIRECTORIO (OBJETOS_LOB) SE GUARDA EN V_BFILE

        DBMS_LOB.OPEN(V_BFILE,DBMS_LOB.LOB_READONLY);       --LUEGO SE ABRE LA IMAGEN (V_BFILE) COMO LECTURA

        DBMS_LOB.LOADFROMFILE(V_TEMP,V_BFILE,DBMS_LOB.GETLENGTH(V_BFILE));      --GUARDAMOS SOBRE (V_TEMP) LA IMAGEN ENCONTRADA (V_BFILE) Y EL TAMANO EN MB O KB

        DBMS_LOB.CLOSE(V_BFILE);        --CERRAMOS LA VARIABLE V_BFILE

        COMMIT;
    END;
end;