-- alter user miusuario identified by minuevapass;


CREATE USER NOMBRE_USER identified BY CONTRASENA;

-- error invalid common user or role name
-- alter session set "_ORACLE_SCRIPT"=true;  

SELECT * FROM ALL_USERS;


-- PERMITE QUE EL USUARIO SE PUEDA CONECTAR CON LA BDD
GRANT CONNECT TO NOMBRE_USER;

-- PERMITE QUE EL USUARIO TENGA UNA SESSION CON LA BDD
GRANT CREATE SESSION TO NOMBRE_USER;

-- LE PERMITE AL USUARIO CREAR TABLAS EN LA BDD
grant create table to NOMBRE_USER;

-- LE PERMITE AL USUARIO TODOS LOS PERMISOS DE SYSTEM
GRANT DBA TO NOMBRE_USER;

-- BLOQUEA O DESBLOQUEA AL USUARIO
ALTER USER NOMBRE_USER ACCOUNT UNLOCK;





ALTER USER NOMBRE_USER ACCOUNT LOCK;

